DROP TABLE IF EXISTS RESULTAT;
DROP TABLE IF EXISTS JOUEUR;

CREATE TABLE RESULTAT (
  PRIMARY KEY (idj, score),
  idj  INT NOT NULL,
  score INT NOT NULL
);

CREATE TABLE JOUEUR (
  PRIMARY KEY (idj),
  idj    INT NOT NULL AUTO_INCREMENT,
  nom    VARCHAR(42),
  prenom VARCHAR(42)
);

ALTER TABLE RESULTAT ADD FOREIGN KEY (idj) REFERENCES JOUEUR (idj);