DROP TABLE IF EXISTS RESULTAT;
DROP TABLE IF EXISTS JOUEUR;
CREATE TABLE IF NOT EXISTS JOUEUR (
  PRIMARY KEY (idj),
  idj INT NOT NULL AUTO_INCREMENT,
  nom VARCHAR(42),
  prenom VARCHAR(42)
);
CREATE TABLE IF NOT EXISTS RESULTAT (
  PRIMARY KEY (idj, scoreRes, dateRes),
  idj INT NOT NULL,
  scoreRes INT NOT NULL,
  dateRes DATE NOT NULL,
  FOREIGN KEY (idj) REFERENCES JOUEUR (idj)
);